apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-badimage
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-badimage
  template:
    metadata:
      labels:
        app: nginx-badimage
    spec:
      containers:
      - name: nginx
        image: nginx:this-image-does-not-exist
