apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pod-failure-alerts
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  groups:
  - name: pod-failure.rules
    rules:
    # ------------------------------
    # 1️⃣ Pod 镜像拉取失败
    - alert: PodImagePullBackOff
      expr: kube_pod_container_status_waiting_reason{reason="ImagePullBackOff"} > 0
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is in ImagePullBackOff"
        description: "Pod {{ $labels.pod }} container {{ $labels.container }} failed to pull image {{ $labels.image }}. Namespace: {{ $labels.namespace }}."
    
    # ------------------------------
    # 2️⃣ Pod 内存 OOMKilled
    - alert: PodOOMKilled
      expr: increase(kube_pod_container_status_last_terminated_reason{reason="OOMKilled"}[5m]) > 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} was OOMKilled"
        description: "Pod {{ $labels.pod }} container {{ $labels.container }} was killed due to out-of-memory (OOMKilled) in the last 5 minutes. Namespace: {{ $labels.namespace }}."

